#include "../int_manipulation.h"
#include "../prime_check.h"

#include "problem_001_005.h"

#include <inttypes.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>

void problem_1(bool verbose) {
    printf("If we list all the natural numbers below 10 that are multiples\n");
    printf("of 3 or 5, we get 3, 5, 6, and 9. The sum of these multiples is\n");
    printf(
        "23. Now find the sum of all the multiples of 3 or 5 below 1000\n\n");

    int64_t res = 0;
    if (verbose) {
        for (int64_t i = 0; i < 1000; i += 1) {
            if ((i % 3 == 0) || (i % 5 == 0)) {
                res += i;
                printf("Current number: %5" PRId64 " Current sum: %5" PRId64
                       "\n",
                       i, res);
            }
        }
    } else {
        for (int64_t i = 0; i < 1000; i += 1) {
            if ((i % 3 == 0) || (i % 5 == 0)) {
                res += i;
            }
        }
    }

    printf("The sum of all numbers below 1000 that are divisible by 3 or 5\n");
    printf("is: %5" PRId64 "\n", res);
}

void problem_2(bool verbose) {
    printf("Each new term in the Fibonacci sequence is generated by adding\n");
    printf("the previous two terms. By starting with 1 and 2, the first\n");
    printf("terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...\n");

    printf("By considering the terms in the Fibonacci sequence whose values\n");
    printf("do not exceed four million, find the sum of the even-valued "
           "terms.\n\n");

    int64_t res = 0, a, b = 2, c = 0;
    if (verbose) {
        for (a = 1; a < 4000000; c = a + b, a = b, b = c) {
            printf("Current fibonacci number: %7" PRId64 "\n", a);
            if (a % 2 == 0 && a < 4000000) {
                res += a;
            }
        }
    } else {
        for (a = 1; a < 4000000; c = a + b, a = b, b = c) {
            if (a % 2 == 0 && a < 4000000) {
                res += a;
            }
        }
    }

    printf("The sum of all even fibonacci numbers below 4 million is: %" PRId64
           "\n",
           res);
}

void problem_3(bool verbose) {
    printf("The prime factors of 13,195 are 5, 7, 13, and 29\n");
    printf("Now what is the largest prime factor of 600,851,475,143?\n\n");

    int64_t big_num = 600851475143;
    /*int64_t res = highest_prime_factor(big_num);*/
    int64_t res = 0;

    if (verbose) {
        for (int64_t i = 3; i <= sqrt(big_num); i += 2) {
            if (big_num % i == 0 && is_prime(i)) {
                printf("Current highest prime factor is %4" PRId64 "\n", i);
                res = i;
            }
        }
    } else {
        for (int64_t i = 3; i <= sqrt(big_num); i += 2) {
            if (big_num % i == 0 && is_prime(i)) {
                res = i;
            }
        }
    }

    printf("The higest prime factor of %" PRId64 " is %" PRId64 "\n", big_num,
           res);
    return;
}

void problem_4(bool verbose) {
    printf("A palindromic number reads the same both ways. The largest "
           "palindrome\n");
    printf("made from the product of two 2-digit numbers is 9009 = 91 x 99.\n");
    printf("Find the largest palindrome made from the product of two 3-digit "
           "numbers.\n\n");

    int64_t res = 0;
    int64_t buf = 0;
    if (verbose) {
        for (int64_t i = 100; i < 1000; i += 1) {
            for (int64_t ii = 100; ii < 1000; ii += 1) {
                buf = i * ii;
                if (buf < res) {
                    continue;
                }

                if (buf == i64_reverse(buf) && buf > res) {
                    printf("Current palindrom product: %6" PRId64
                           " Digits: %" PRId64 " %" PRId64 "\n",
                           buf, i, ii);
                    res = i * ii;
                }
            }
        }
    } else {
        for (int64_t i = 100; i < 1000; i += 1) {
            for (int64_t ii = 100; ii < 1000; ii += 1) {
                buf = i * ii;
                if (buf < res) {
                    continue;
                }

                if (buf == i64_reverse(buf) && buf > res) {
                    res = i * ii;
                }
            }
        }
    }

    printf(
        "The highest palindrom product made by two 3 digit numbers is %" PRId64
        "\n",
        res);
    return;
}

void problem_5(bool verbose) {
    printf("2520 is the smallest number that can be divided by each of the "
           "numbers\n");
    printf(
        "from 1 to 10 without any remainder. What is the smallest positive\n");
    printf("number that is evenly divisible (divisible with no remainder)\n");
    printf("by all of the numbers from 1 to 20?\n\n");

    int64_t res = 0;
    int64_t highest_divisor = 20;

    if (verbose) {
        printf(
            "Verbose mode for this problem is way way slower, so be warned\n");
        for (int64_t i = highest_divisor;; i += highest_divisor) {
            printf("\rCurrent number: %9" PRId64, i);
            if (is_divisible_by_1_through_n(i, highest_divisor)) {
                res = i;
                break;
            }
        }
        printf("\n");
    } else {
        for (int64_t i = highest_divisor;; i += highest_divisor) {
            if (is_divisible_by_1_through_n(i, highest_divisor)) {
                res = i;
                break;
            }
        }
    }

    printf(
        "The lowest number that is evenly divisible by 1 through 20 is %" PRId64
        "\n",
        res);
    return;
}
