#!/usr/bin/env bash

gcd() {
	if (($1 % $2 == 0)); then
		echo $2
	else
		echo $(gcd $2 $(( $1 % $2 )))
	fi
}

if ! command -v factor &>/dev/null; then
	croi_factor() {
		input=$1
		x=2
		y=2
		d=1

		while [[ $d == 1 ]]; do
			x=$(((($x*$x) + 1) % $input))
			y=$((((((($y * $y) + 1) % $input) * ((($y * $y) + 1) % $input)) + 1) % $input))
			abs_x_y=$((${x#-} - ${y#-}))
			d=$(gcd $abs_x_y $input)
		done

		if [[ $d == $input ]]; then
			return 1
		else
			echo $d
		fi
	}
fi

problem_01() {
	result=0

	for i in {3..999}; do
		if [[ $(($i % 3)) == 0 ]]; then
			result=$(($result+$i))
		elif [[ $(($i % 5)) == 0 ]]; then
			result=$(($result+$i))
		fi
	done
	
	echo $result
}

problem_02() {
	result=0
	fib_a=0
	fib_b=1

	while [[ $fib_a -lt 4000000 ]]; do
		fib_c=$((fib_a + fib_b))
		fib_a=$fib_b
		fib_b=$fib_c

		if [[ $(($fib_a % 2)) == 0 ]]; then
			result=$(($result+$fib_a))
		fi
	done

	echo $result
}

problem_03() {
	num_1=600851475143
	result=0

	if command -v factor &>/dev/null; then
		result=$(factor $num_1 | awk '{print $NF}')
	elif ! command -v format &>/dev/null; then
		result=$(croi_factor $num_1)
	fi

	echo $result
}
