[package]
name = "random_code_croisen"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
gmp-mpfr-sys = "1.5.2"
gnuplot = "0.0.37"
[[bin]]
name = "making_the_z_table"
test = false
bench = false
