#include <inttypes.h>
#include <stdint.h>

#include "003_col_limited_printf.h"
#include "problem_001_009.h"

void problem_002(void)
{

    col_limited_printf(80, 0, "Problem: 002 - Even Fibonacci Numbers\n");
    col_limited_printf(
        80, 0,
        "Description: Each new term in the Fibonacci sequence is generated by "
        "adding the previous two terms. By starting with 1 and 2, the first 10 "
        "terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \n"
    );
    col_limited_printf(
        80, 0,
        "Goal: By considering the terms in the Fibonacci sequence whose values "
        "do not exceed four million, find the sum of the even-valued terms.\n"
    );

    uint64_t a = 1, b = 2, c = 0;
    uint64_t res = 0;
    while (a < 4000000) {
        res += (a < 4000000 && a % 2 == 0) * a;
        c    = a + b;
        a    = b;
        b    = c;
    }

    col_limited_printf(80, 0, "Answer: %" PRIu64 "\n\n", res);
}
